![dvd_image](dvd_image.jpg)

A DVD rental company needs your help! They want to figure out how many days a customer will rent a DVD for based on some features and has approached you for help. They want you to try out some regression models which will help predict the number of days a customer will rent a DVD for. The company wants a model which yeilds a MSE of 3 or less on a test set. The model you make will help the company become more efficient inventory planning.

The data they provided is in the csv file `rental_info.csv`. It has the following features:
- `"rental_date"`: The date (and time) the customer rents the DVD.
- `"return_date"`: The date (and time) the customer returns the DVD.
- `"amount"`: The amount paid by the customer for renting the DVD.
- `"amount_2"`: The square of `"amount"`.
- `"rental_rate"`: The rate at which the DVD is rented for.
- `"rental_rate_2"`: The square of `"rental_rate"`.
- `"release_year"`: The year the movie being rented was released.
- `"length"`: Lenght of the movie being rented, in minuites.
- `"length_2"`: The square of `"length"`.
- `"replacement_cost"`: The amount it will cost the company to replace the DVD.
- `"special_features"`: Any special features, for example trailers/deleted scenes that the DVD also has.
- `"NC-17"`, `"PG"`, `"PG-13"`, `"R"`: These columns are dummy variables of the rating of the movie. It takes the value 1 if the move is rated as the column name and 0 otherwise. For your convinience, the reference dummy has already been dropped.

In [10]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.ensemble import RandomForestRegressor

df = pd.read_csv("rental_info.csv")
df.head(10)

                 rental_date  ... rental_rate_2
0  2005-05-25 02:54:33+00:00  ...        8.9401
1  2005-06-15 23:19:16+00:00  ...        8.9401
2  2005-07-10 04:27:45+00:00  ...        8.9401
3  2005-07-31 12:06:41+00:00  ...        8.9401
4  2005-08-19 12:30:04+00:00  ...        8.9401
5  2005-05-29 16:51:44+00:00  ...        8.9401
6  2005-06-17 19:42:42+00:00  ...        8.9401
7  2005-07-09 18:23:46+00:00  ...        8.9401
8  2005-07-27 13:16:28+00:00  ...        8.9401
9  2005-08-21 13:53:52+00:00  ...        8.9401

[10 rows x 15 columns]

In [11]:
df["rental_date"] = pd.to_datetime(df["rental_date"])
df["return_date"] = pd.to_datetime(df["return_date"])

#Calculamos los dias de renta
df["rental_length_days"] = (df["return_date"] - df["rental_date"]).dt.days
df["rental_length_days"].head(10)

0    3
1    2
2    7
3    2
4    4
5    3
6    5
7    4
8    1
9    3
Name: rental_length_days, dtype: int64

In [12]:
#Creación de columnas con información binaria 0,1 para las features de interés
df["deleted_scenes"] = np.where(df["special_features"].str.contains("Deleted Scenes"), 1, 0)
df["behind_the_scenes"] = np.where(df["special_features"].str.contains("Behind the Scenes"), 1, 0)
df.head(10)

                rental_date  ... behind_the_scenes
0 2005-05-25 02:54:33+00:00  ...                 1
1 2005-06-15 23:19:16+00:00  ...                 1
2 2005-07-10 04:27:45+00:00  ...                 1
3 2005-07-31 12:06:41+00:00  ...                 1
4 2005-08-19 12:30:04+00:00  ...                 1
5 2005-05-29 16:51:44+00:00  ...                 1
6 2005-06-17 19:42:42+00:00  ...                 1
7 2005-07-09 18:23:46+00:00  ...                 1
8 2005-07-27 13:16:28+00:00  ...                 1
9 2005-08-21 13:53:52+00:00  ...                 1

[10 rows x 18 columns]

In [13]:
#Definimos nuestro dataset de entrenamiento y validación quitando datos que tratamos de predecir
cols_to_drop = ["rental_date", "return_date", "special_features", "rental_length_days"]
X = df.drop(columns=cols_to_drop)
y = df["rental_length_days"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=9)

In [14]:
#Se utilizó Random Forest para hacer regresión
rf = RandomForestRegressor(n_estimators=100, random_state=9)
rf.fit(X_train, y_train)

y_pred = rf.predict(X_test)
mse = mean_squared_error(y_test, y_pred)

best_model = rf
best_mse = mse

print(f"Best MSE : {best_mse}")

Best MSE : 2.030141907417274

In [14]:
# Best MSE < 3, cumple con el objetivo.